name: create_day_pages

on:
  workflow_dispatch:

jobs:

  create_notion_morning_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.0"
      - name: Create daily pages
        run: go run cmd/morning_pages/main.go
        env:
          MORNING_WORKFLOW_API_TOKEN: ${{ secrets.MORNING_WORKFLOW_API_TOKEN }}
